### ISSUE TITLE
✨🔧  Add github templates for bugs and feature requests

### ISSUE THREAD

**Issue by bal7hazar** [z-korp/zknight-contracts#5]

**Comment by hymns12** [comment]
Hi good day can i work on this project

**Comment by bal7hazar** [comment]
@hymns12 sorry we dont have any grant allocated for this rn

**Comment by hymns12** [comment]
yep at @Bal7hazar  i can still work on it 
do you want me to work on it??

**Comment by bal7hazar** [comment]
> yep at @Bal7hazar i can still work on it do you want me to work on it??

@hymns12 thank you for your interest, the issue has been closed since it is not relevant anymore
